### ISSUE TITLE
create_client function is not async

### ISSUE THREAD

**Issue by newsbubbles** [Atticuszz/supabase-py-async#1]
in your example, you use 

await create_async_client ...

first off this is not the name of the function.  It is just create_client... and it is not defined as async.

**Comment by Atticuszz** [comment]
> in your example, you use 
> 
> await create_async_client ...
> 
> first off this is not the name of the function.  It is just create_client... and it is not defined as async.

oh iam sorry that，md is created by gpt4，i 'll correct it right now ，thank u bro
